---
title: "download"
output: html_document
---

```{r}
library(tidyverse)

ids <- c("aputron","gpemelianov","yoo-bh","seokjin-oh","treenbird19","jinjulee119")
homedirs <- c(rep("researcheweb",6))
destdir <- "download/"

i <- 1
url <- paste0("https://github.com/", ids[i],"/",homedirs[i],"/raw/main/partdb.xlsx")
destfile <- paste0(destdir, ids[i], ".xlsx")
download.file(url, destfile)

for(i in 1:length(ids)){
  url <- paste0("https://github.com/",ids[i], "/",homedirs[i], "/raw/main/partdb.xlsx")
  destfile <- paste0(destdir, ids[i], ".xlsx")
  try(download.file(url,destfile))
  cat(i,"\n");flush.console()
}
```


```{r}
library(readxl)
library(tidyverse)

destdir <- "download/"
filenames <- dir(path = destdir, pattern = "*.xlsx")

tmp1 <- list()
tmp2 <- list()
tmp3 <- list()


for(i in 1:length(filenames)){
  destfile <- paste0(destdir, filenames[i])
  tmp1[[i]] <- read_excel(destfile, sheet=1, skip=0,col_names = T)
  tmp2[[i]] <- read_excel(destfile, sheet=2, skip=0,col_names = T)
  tmp3[[i]] <- read_excel(destfile, sheet=3, skip=0,col_names = T)
}

dat <- lapply(tmp1, function(x) mutate_at(x, .vars = c("year"), as.character))

igem_team <- do.call(bind_rows, dat)
igem_part <- do.call(bind_rows, tmp2)
igem_obs <- do.call(bind_rows, tmp3)


```

```{r}
install.packages("writexl")
library(writexl)

write_xlsx(igem_team, path = "igem_team.xlsx")
write_xlsx(igem_part, path = "igem_part.xlsx")
write_xlsx(igem_obs, path = "igem_obs.xlsx")


```

